language: c
before_install:
 - sudo apt-get install -qq raptor2-utils
 - sudo apt-get install -qq yajl-tools
 - sudo apt-get install -qq jq
 - sudo apt-get install -qq graphviz
 - sudo apt-get install -qq tidy
 - sudo apt-get install -qq libxml2-utils

env:

script:
  -  bash  ./run.sh accounts-api/accounts/openrdf-sesame/authorization/
  -  bash  ./run.sh extensions/graph-store-protocol
  -  bash  ./run.sh extensions/sparql-protocol/collation
  -  bash  ./run.sh extensions/sparql-protocol/describe
  -  bash  ./run.sh extensions/sparql-protocol/meta-data
  -  bash  ./run.sh extensions/sparql-protocol/parameters
  -  bash  ./run.sh extensions/sparql-protocol/provenance
  -  bash  ./run.sh extensions/sparql-protocol/revisions
  -  bash  ./run.sh extensions/sparql-protocol/sparql-operators
  -  bash  ./run.sh extensions/sparql-protocol/temporal-data
  -  bash  ./run.sh extensions/sparql-protocol/values
  -  bash  ./run.sh extensions/sparql-protocol/views
  -  bash  ./run.sh extensions/sparql-protocol/xpath-operators
  -  bash  ./run.sh sparql-protocol
  -  bash  ./run.sh sparql-graph-store-http-protocol
  -  bash  ./run.sh tickets
  -  bash  ./run.sh triple-pattern-fragments
  -  bash  ./run.sh web-ui

notifications:
  email:
    recipients:
      - james@dydra.com
